services:
  postgres:
    image: postgres:17-alpine
    container_name: assignment_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: assignment_backend
    restart: always
    tty: true
    stdin_open: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Information
      - ConnectionStrings__DefaultConnection=Host=assignment_postgres;Port=5432;Database=mydb;Username=postgres;Password=mysecretpassword
      - JwtSettings__Issuer=AssignmentManager.API
      - JwtSettings__Audience=AssignmentManager.UI
      - JwtSettings__PrivateKey=-----BEGIN PRIVATE KEY-----MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2hY+ghOSD0zmLrqmRJa8vj47hgVE3+AudExkTt5mk9+5NjEqcT1PQrqdM7goENZrrwIpQUk+fPWy+1hfDEIJfp/dtZScRUFx0jmabjtg9i9a5y1gpcEQF96V2hc7MsPuSbaj0VDuRZtEMhT1Fyb/4ALzRSEFymQuHPB7LgbkqhFKliiqdT9pfX4lhNXIPMajDGGbN2OVbBjut+AdotGVzjS9jDAXBHUx936pKVgE/LffEur4/XLiOslI8dmTcUCUE3gAuHezkLpUXTzIU3N22j58PtNopWFvO6S/Kh0EOgmNS5tiEd+9B300WxxjgCNu6EsdJT90JFWU/885ILSB9AgMBAAECggEAOx7QAwKIslp8zU3qBuXZ9OHfOhQVJrflqx9AhC54SgM04VGL6U2YrIOmFTkVbX+firV3F8VRnRbcXoQidkCmui1B6+FT4jvRdr+ZZNHEIUtmZhADooiGwBgTNGzrK0o4cpmqnFmcYeCX3iJaUnyi/cXfYzqwWFpSbZ9/qhN+0tI1mPyk2rpj+lNumOpLtPTsqe/w4VcyJvR12N88BPSZbkr4RsdyuoVzU5EiZvpXZ9BCKTepPkiHYwVQrGqjplP/z9hDHiFrmUo1vjVMhay3HyFHBnRwLqqq7NKwG16QAsG2hGu65BlgAvIHV687Tv7SiKKZ+KhiE6806LdVn7NS0QKBgQDZ1yaxZgXzCtt4YW2JME72oNAecc7ZarWwoFYs6asbnCMkDGD9/YdffC20yUpBuqUByH3wUZ3uVgJpHLxN83DGXYpJM0iVZy02vrvi39Hmo2cVvKicxrc5qmw+T51iUhJimyyFuPHNws+IMKHlcijW4q3ijx9XItejgVFkwrZu1wKBgQDWfpNaD8ps/U7x7fhhqwWZyZCneEH19uRJe0O65d9jkNZCgH5wqIWZWW9RfjDc3mgilnsx5ynbyRqRpbFPMSM3DU03ElGhc/aG0BKsam11ODNQ1zoVHgAYWzgMRpdXjorO0E1cluSUcazOF4KaJk/pvPIm0pHVrzv3ACOQ2NskywKBgB6JdYgauCzI0dk/Nx6rIfaatnH+HDQILG4VG99x5iWZrqdoANS6DJcLDlEwgnNSWb01QMpGdrApaG8Zsx/uR1nXVQJL6Rnge8sX07jLDV6ae2Hlr3FCvf6ccE4P1Q0qWh9uh0A7m9HvRC5gOuGyLh1pa1y+GXOak8X8488PKInDAoGAcvq5DG8oiNIkzoVNPzXJM84cD9nkKfCmIUnFXdu5qwrKAC4XGVcM/s41YQ7vLIbAdcIK2g5bnuinqGmUqanigbFMsffM8GpUPaIuUGRgtpRg1bX5+bXyQRws6E+y8wmDGSgKQFbWw0hIZNWveeiNr/NML0lzSYO89kQJzKyilI8CgYEAsirKOf7p5Z6sya2MHlPdr7RaIbbgmXoLmKRWpBq7gLrkGFziLRg1qZL/8EgafFissqMu0Emru1tbJU4sbQ9i++5Ho0etgjfmG5I7wcbVhNF0kBTs+FcxjbuBan3sO+43tvm7zLftLrpISOqDzyKohYBdMVsMqCiFLkorJZjEM4o=-----END PRIVATE KEY-----
      - JwtSettings__PublicKey=-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtoWPoITkg9M5i66pkSWvL4+O4YFRN/gLnRMZE7eZpPfuTYxKnE9T0K6nTO4KBDWa68CKUFJPnz1svtYXwxCCX6f3bWUnEVBcdI5mm47YPYvWuctYKXBEBfeldoXOzLD7km2o9FQ7kWbRDIU9Rcm/+AC80UhBcpkLhzwey4G5KoRSpYoqnU/aX1+JYTVyDzGowxhmzdjlWwY7rfgHaLRlc40vYwwFwR1Mfd+qSlYBPy33xLq+P1y4jrJSPHZk3FAlBN4ALh3s5C6VF08yFNzdto+fD7TaKVhbzukvyodBDoJjUubYhHfvQd9NFscY4AjbuhLHSU/dCRVlP/POSC0gfQIDAQAB-----END PUBLIC KEY-----
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8080/api
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8080/api
    container_name: assignment_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
  pgadmin-data: